from xtrack.beam_elements import (
    Solenoid,
    Bend,
    Quadrupole,
    Sextupole,
    Octupole,
    Marker,
    Cavity,
    Drift,
)
from xtrack.monitors import ParticlesMonitor

xsuite_conversion_rules = {
    "dipole": Bend,
    "solenoid": Solenoid,
    "quadrupole": Quadrupole,
    "sextupole": Sextupole,
    "octupole": Octupole,
    "beam_position_monitor": ParticlesMonitor,
    "beam_arrival_monitor": Drift,
    "bunch_length_monitor": Drift,
    "screen": ParticlesMonitor,
    "marker": ParticlesMonitor,
    "rcollimator": Drift,
    "collimator": Drift,
    "monitor": ParticlesMonitor,
    "wall_current_monitor": Drift,
    "integrated_current_transformer": Drift,
    "faraday_cup": Drift,
    "cavity": Cavity,
    "rf_deflecting_cavity": Cavity,
    "aperture": Drift,
    "shutter": Drift,
    "valve": Drift,
    "bellows": Drift,
    "cleaner": Drift,
    "lscdrift": Drift,
    "csrdrift": Drift,
    "edrift": Drift,
    "drift": Drift,
    "kicker": Bend,
    "scatter": Marker,
    "apcontour": Marker,
    "center": Marker,
    "fel_modulator": Drift,
    "wiggler": Drift,
    "charge": Marker,
    "wakefield": Marker,
    "watch_point": ParticlesMonitor,
}
