"""
SIMBA Wavefronts Module

This module defines the base class and utilities for representing photon wavefronts generated by
free-electron lasers or wigglers in synchrotrons

****WARNING****
This is a work-in-progress. Many features are not yet implemented

For now, the only interface to wavefronts is based on the openpmd-beamphysics implementation.
Only GENESIS-style `field` objects are supported.

The `wavefrontGroup` class is used for loading and analysing a group of wavefronts,
for example from a directory.

Classes:
    - :class:`~simba.Modules.Wavefronts.wavefront`: Generic container for a wavefront.

    - :class:`~simba.Modules.Beams.wavefrontGroup`: Container for a group of wavefronts.
"""
import numpy as np
import os
import glob
from pydantic import BaseModel
from typing import Dict
from pmd_beamphysics.wavefront.wavefront import Wavefront


class wavefrontGroup(BaseModel):
    """
    Class for grouping together multiple wavefronts. These distributions can be loaded in
    from a directory, for example, using the function
    :func:`~simba.Modules.Wavefronts.load_directory`.

    ****WARNING****
    This is a work-in-progress. Many features are not yet implemented

    For now, the only interface to wavefronts is based on the openpmd-beamphysics implementation.
    Only GENESIS-style `field` objects are supported.
    """

    sddsindex: int = 0
    """Index for SDDS files"""

    wavefronts: Dict = {}
    """Dictionary containing the :class:`~simba.Modules.Wavefronts.wavefront` objects,
    keyed by (file)name"""

    def __repr__(self):
        return repr(list(self.wavefronts.keys()))

    def __len__(self):
        return len(list(self.wavefronts.keys()))

    def __getitem__(self, key):
        if isinstance(key, int):
            return list(self.wavefronts.values())[key]
        elif isinstance(key, slice):
            return wavefrontGroup(wavefronts=list(self.wavefronts.items())[key])
        else:
            return getattr(self, key)

    def __init__(self, filenames=[], wavefronts=[], *args, **kwargs):
        super(wavefrontGroup, self).__init__(*args, **kwargs)
        self.sddsindex = 0
        self.wavefronts = dict()
        for k, v in wavefronts:
            self.wavefronts[k] = v
        if isinstance(filenames, str):
            filenames = [filenames]
        for f in filenames:
            self.add(f)

    def add(self, filename):
        if isinstance(filename, str):
            filename = [filename]
        for file in filename:
            if os.path.isdir(file):
                self.add_directory(file)
            elif os.path.isfile(file):
                file = file.replace("\\", "/")
                try:
                    self.wavefronts[file] = Wavefront.from_genesis4(file)
                except Exception:
                    if file in self.wavefronts:
                        del self.wavefronts[file]

    def getWavefront(self, wavefront):
        for b in self.wavefronts:
            if wavefront == os.path.splitext(os.path.basename(b))[0]:
                return self.wavefronts[b]
        return None

    def getWavefronts(self):
        return {os.path.splitext(os.path.basename(b))[0]: b for b in self.wavefronts.keys()}


def load_directory(directory=".", types={"Genesis": ".fld.h5"}, verbose=False) -> wavefrontGroup:
    """
    Load in all wavefront files from a directory and create a
    :class:`~simba.Modules.Wavefronts.wavefrontGroup` object.

    Parameters
    ----------
    directory: str
        Directory from which to load the files
    types: Dict
        Wavefront file types to load
    verbose: bool
        If true, print progress

    Returns
    -------
    :class:`~simba.Modules.Wavefronts.wavefrontGroup`
        A new `wavefrontGroup`.
    """
    wg = wavefrontGroup()
    if verbose:
        print("Directory:", directory)
    for code, string in types.items():
        wavefront_files = glob.glob(directory + "/*" + string)
        if verbose:
            print(code, [os.path.basename(t) for t in wavefront_files])
        wg.add(wavefront_files)
    return wg