"""
SIMBA MAD-X Module

Various objects and functions to handle MAD-X lattices and tracking. The
interaction with MAD-X is handled through the `cpymad`_ library, which embeds
the MAD-X interpreter in the Python process; see the `MAD-X manual`_ for
details of the underlying commands.

    .. _cpymad: https://hibtc.github.io/cpymad/
    .. _MAD-X manual: https://madx.web.cern.ch/webguide/manual.html

The lattice (including explicit drifts) is converted into one or more MAD-X
``SEQUENCE`` blocks via the LAURA
:class:`~laura.translator.converters.section.SectionLatticeTranslator`
machinery. Since MAD-X reference momentum is fixed for a given ``BEAM``
statement (magnet strengths are normalised to it, and tracking coordinates are
canonical w.r.t. it), the lattice is split into segments at each accelerating
(RF) cavity. Each segment is tracked with the local reference momentum taken
from the tracked bunch itself, and the particle coordinates are re-referenced
between segments -- mirroring the ``always_change_p0`` behaviour used for
ELEGANT and the internal energy bookkeeping of Ocelot, so that the beam
evolution can be interpreted in the same way as for the other tracking codes.

Two tracking modes are available:

- Full-beam tracking (default): every macro-particle in the input
  distribution is tracked with the thin-lens tracking module (``TRACK`` ...
  ``START`` ... ``RUN``), and output beam distributions are written (in
  OpenPMD HDF5 format) at every diagnostic (``Screen``, ``Marker`` and
  ``BPM``) in the lattice, as well as at the end of the line.

- ``single_particle`` mode: only the beam centroid (plus a small set of probe
  trajectories used to build the linear map by finite differences) is tracked
  through each segment with standard MAD-X tracking. The output beam at the
  end of the line is then generated by applying the resulting transformation
  (centroid + linear map) to the initial particle distribution. No
  intermediate diagnostic outputs are produced in this mode.

In both cases a Twiss summary file (``<lattice>_twiss.madx.hdf5``) is written,
containing both the MAD-X model optics (Twiss functions, dispersion, phase
advances) and beam-distribution statistics (momentum, sizes, bunch length,
emittances), which can be loaded through
:func:`simba.Modules.Twiss.load_directory` in the same way as the output of
the other tracking codes.

Classes:
    - :class:`~simba.Codes.MADX.MADX.madxLattice`: The MAD-X lattice object,
      used for converting the elements defined in the
      :class:`~simba.Framework_objects.frameworkLattice` into MAD-X sequences,
      and for tracking through them using `cpymad`.
"""

import os
import re
from copy import deepcopy
from warnings import warn

import numpy as np
from yaml import safe_load

from ...Framework_objects import frameworkLattice
from ...Modules import Beams as rbf
from ...Modules import constants
from ...Modules.units import UnitValue
from ...Modules.Twiss.madx import save_madx_twiss_hdf

from laura.translator.converters.converter import translate_elements
from laura.translator.utils.functions import (
    sanitize_string,
    madx_functional_definitions,
)

from typing import Dict, List, Any

with open(
    os.path.dirname(os.path.abspath(__file__)) + "/madx_defaults.yaml",
    "r",
) as infile:
    madxglobal = safe_load(infile)

# electron rest energy in eV
speed_of_light = constants.speed_of_light
elementary_charge = constants.elementary_charge

# MAD-X particle names for the species supported by the beam object
madx_particle_names = {
    "electron": "electron",
    "positron": "positron",
    "proton": "proton",
    "antiproton": "antiproton",
}


class madxLattice(frameworkLattice):
    """
    Class for defining the MAD-X lattice object, used for converting the
    elements defined in the :class:`~simba.Framework_objects.frameworkLattice`
    into MAD-X ``SEQUENCE`` definitions and for tracking through them with
    `cpymad <https://hibtc.github.io/cpymad/>`_.

    The lattice is split into segments at each RF cavity so that the MAD-X
    reference momentum (to which magnet strengths and canonical track
    coordinates are normalised) can follow the acceleration of the beam; the
    particle coordinates are transformed between the segment-local reference
    frames via the generic :class:`~simba.Modules.Beams.beam` object.

    If :attr:`~single_particle` is False (the default), the full particle
    distribution is tracked and beam distributions are written at each
    diagnostic (`Screen`, `Marker` and `BPM`) in the lattice. If True,
    standard (single-particle) MAD-X tracking is performed for the beam
    centroid and a set of probe trajectories, and only the output beam at the
    end of the line is generated, based on a transformation (centroid offset
    plus finite-difference linear map) of the initial distribution.
    """

    code: str = "madx"
    """String indicating the lattice object type"""

    trackBeam: bool = True
    """Flag to indicate whether to track the beam"""

    single_particle: bool = False
    """If True, perform standard (single particle) MAD-X tracking and only
    generate the output beam at the end of the line based on a transformation
    of the initial distribution. If False (default), track the full particle
    distribution and output beam files at all diagnostics."""

    particle_definition: str = None
    """Initial particle distribution as a string"""

    madxglobal: Dict = {}
    """Global settings for MAD-X, read in from
    `settings["global"]["MADXsettings"]` and `madx_defaults.yaml`"""

    nslice_quadrupole: int = 4
    """Number of MAKETHIN slices for quadrupoles"""

    nslice_sbend: int = 8
    """Number of MAKETHIN slices for bending magnets"""

    cavity_model: str = "rsmatrix"
    """Transverse model for accelerating (RF) cavities:

    - ``rsmatrix`` (default): the transverse motion through the structure is
      described by a first-order MAD-X ``MATRIX`` element containing the
      Rosenzweig-Serafini accelerating-structure matrix (as also used by
      Ocelot), which accounts for adiabatic damping and ponderomotive (RF)
      focusing; the energy gain and RF curvature are applied by a thin
      ``RFCAVITY`` kick. In the fixed-reference-momentum canonical
      coordinates of a segment this matrix is exactly symplectic.

    - ``sliced``: the cavity is subdivided into :attr:`~nslice_rfcavity` thin
      RF kicks with exact drifts in between (adiabatic damping only).

    - ``thin``: a single thin RF kick at the centre of the structure (the
      plain MAD-X MAKETHIN treatment)."""

    nslice_rfcavity: int = 10
    """Number of longitudinal slices for RF cavities when
    :attr:`~cavity_model` is ``sliced``. Since the MAD-X thin-lens
    tracking module applies RF cavities as single kicks (MAKETHIN does not
    subdivide them), cavities are subdivided at the sequence level into
    `nslice_rfcavity` sub-cavities, each carrying 1/n of the voltage. The
    (exact) drifts between the resulting thin kicks then reproduce the
    adiabatic damping of the transverse coordinates along an accelerating
    structure."""

    nslice_default: int = 1
    """Default number of MAKETHIN slices for all other thick elements"""

    makethin_style: str = "teapot"
    """Slicing style for the MAD-X MAKETHIN command"""

    makedipedge: bool = True
    """Flag to control the generation of DIPEDGE elements in MAKETHIN"""

    maxaper: List = [100.0, 100.0, 100.0, 100.0, 1000.0, 1000.0]
    """Upper limits for the particle coordinates [x, px, y, py, t, pt] used by
    the MAD-X RUN command; kept deliberately large so that particles are not
    artificially collimated (consistent with the other tracking codes)"""

    write_model_twiss: bool = True
    """If True, compute the MAD-X model Twiss parameters (via the TWISS
    command) for each segment and include them in the Twiss output file"""

    fd_delta: float = 1e-6
    """Finite-difference step used to build the linear map in
    ``single_particle`` mode"""

    segments: List = []
    """List of lattice segments; each segment is a list of element names and
    is tracked with a constant MAD-X reference momentum"""

    seqstrings: List = []
    """MAD-X SEQUENCE definitions for each segment"""

    pin: Any = None
    """Initial particle distribution as a :class:`~simba.Modules.Beams.beam`"""

    pout: Any = None
    """Final particle distribution as a :class:`~simba.Modules.Beams.beam`"""

    tws: Dict = {}
    """Dictionary of arrays containing the collected Twiss/beam-statistics
    data along the lattice"""

    beam_data: Dict = {}
    """Data containing beam statistics at each observation point"""

    model_twiss: Dict = {}
    """MAD-X model Twiss parameters at each element, keyed by element name"""

    segment_p0c: Dict = {}
    """MAD-X reference momentum [eV/c] of the segment each element belongs to,
    keyed by element name. Used to convert the canonical model Twiss functions
    back to trace space (see :func:`~postProcess`)"""

    output_beams: Dict = {}
    """Beam distributions at each observation point, keyed by element name"""

    ref_s: float = None
    """Reference s position"""

    ref_idx: int = None
    """Reference particle index"""

    logfile: Any = None
    """File handle for the MAD-X log file"""

    def model_post_init(self, __context):
        super().model_post_init(__context)
        self.madxglobal = deepcopy(madxglobal)
        if "MADXsettings" in list(self.settings["global"].keys()):
            for k, v in self.settings["global"]["MADXsettings"].items():
                self.madxglobal.update({k: v})
        # settable configuration fields, from global settings or the lattice
        # file block
        for f in list(madxglobal.keys()) + ["trackBeam"]:
            if f in self.madxglobal:
                setattr(self, f, self.madxglobal[f])
            if f in self.file_block:
                setattr(self, f, self.file_block[f])
        if (
            "input" in self.file_block
            and "particle_definition" in self.file_block["input"]
        ):
            if (
                self.file_block["input"]["particle_definition"]
                == "initial_distribution"
            ):
                self.particle_definition = "laser"
            else:
                self.particle_definition = self.file_block["input"][
                    "particle_definition"
                ]
        else:
            self.particle_definition = self.start
        self.segments = []
        self.seqstrings = []
        self.beam_data = {}
        self.model_twiss = {}
        self.segment_p0c = {}
        self.output_beams = {}
        self.tws = {}

    # ------------------------------------------------------------------
    # Lattice generation
    # ------------------------------------------------------------------
    @property
    def particle_rest_energy_eV(self) -> float:
        """Rest energy of the tracked particles in eV"""
        try:
            return float(
                np.mean(self.global_parameters["beam"].particle_rest_energy_eV.val)
            )
        except Exception:
            return constants.m_e * speed_of_light**2 / elementary_charge

    def segmentElements(self) -> List:
        """
        Split the lattice (including explicit drifts) into segments, breaking
        after each RF cavity. Within each segment the beam energy -- and
        therefore the MAD-X reference momentum -- is constant, which allows
        normalised magnet strengths to be interpreted at the local design
        momentum, in the same way as for the other supported tracking codes.

        Returns
        -------
        List
            A list of segments, each a list of element names (in order).
        """
        elements_with_drifts = self.section.createDrifts()
        self._elements_with_drifts = elements_with_drifts
        self._elem_dict = translate_elements(
            list(elements_with_drifts.values()),
            master_lattice=self.global_parameters["master_lattice"],
            directory=self.global_parameters["master_subdir"],
        )
        self._sval_in = self.section.get_s_values(as_dict=True, at_entrance=True)
        self._sval_out = self.section.get_s_values(as_dict=True, at_entrance=False)
        segments = []
        current = []
        for name, elem in self._elem_dict.items():
            current.append(name)
            # segment boundaries at accelerating cavities (but not
            # transverse deflecting cavities, which do not change the
            # reference momentum)
            if elem.hardware_type.lower() == "rfcavity":
                segments.append(current)
                current = []
        if len(current) > 0:
            segments.append(current)
        self.segments = segments
        return segments

    def writeElements(self) -> str:
        """
        Create the MAD-X ``SEQUENCE`` definitions for all segments of the
        lattice, using ``refer=centre`` positioning (as required by the MAD-X
        ``MAKETHIN`` command) and set :attr:`~seqstrings`.

        Returns
        -------
        str
            The full lattice represented as a string compatible with MAD-X
        """
        self.segmentElements()
        self.seqstrings = []
        self._design_energy = self.initial_energy()
        fulltext = madx_functional_definitions(self.section.functional_definitions)
        for iseg, segnames in enumerate(self.segments):
            seqname = self.segment_name(iseg)
            seg_s0 = self._sval_in[segnames[0]]
            seg_s1 = self._sval_out[segnames[-1]]
            seg_len = seg_s1 - seg_s0
            lines = [f"{seqname}: sequence, refer=centre, l = {seg_len};"]
            for name in segnames:
                d = self._elem_dict[name]
                if getattr(d, "subelement", False):
                    at = (
                        d.physical.start.z
                        - self.startObject.physical.start.z
                        - seg_s0
                        + d.physical.length / 2.0
                    )
                else:
                    at = self._sval_in[name] - seg_s0 + d.physical.length / 2.0
                estr = d.to_madx(at=at).strip()
                if d.hardware_type.lower() == "rfcavity":
                    if self.cavity_model.lower() == "rsmatrix":
                        estr, self._design_energy = self.rs_matrix_cavity(
                            estr, d.physical.length, at, self._design_energy
                        )
                    elif (
                        self.cavity_model.lower() == "sliced"
                        and self.nslice_rfcavity > 1
                    ):
                        estr = self.slice_cavity(estr, d.physical.length, at)
                lines.append(estr)
            lines.append("endsequence;")
            seqstr = "\n".join(lines)
            self.seqstrings.append(seqstr)
            fulltext += f"\n! ------------------ segment {iseg} ------------------\n"
            fulltext += seqstr + "\n"
        return fulltext

    def segment_name(self, iseg: int) -> str:
        """MAD-X compatible name for lattice segment `iseg`"""
        return f"{sanitize_string(self.objectname)}_seg_{iseg}"

    def initial_energy(self) -> float:
        """
        Total energy [eV] of the input beam (used to accumulate the design
        energy along the segments when building the cavity matrices). Returns
        0 if no beam has been loaded yet.
        """
        for bm in [self.pin, self.global_parameters.get("beam", None)]:
            try:
                if bm is not None and len(bm.x.val) > 0:
                    return float(np.mean(bm.energy.val))
            except Exception:
                continue
        return 0.0

    def parse_madx_element(self, estr: str) -> tuple:
        """
        Parse a MAD-X element definition string into its name, type and
        attribute dictionary.

        Parameters
        ----------
        estr: str
            MAD-X element definition, e.g. ``name: rfcavity, volt = 1, ...;``

        Returns
        -------
        tuple
            (name, type, attributes)
        """
        head, _, body = estr.partition(":")
        elemname = head.strip()
        body = body.strip().rstrip(";")
        parts = [p.strip() for p in body.split(",")]
        etype = parts[0].strip().lower()
        attrs = {}
        for p in parts[1:]:
            mm = re.match(r"^(\w+)\s*=\s*(.+)$", p)
            if mm:
                attrs[mm.group(1).lower()] = mm.group(2).strip()
        return elemname, etype, attrs

    def rs_matrix_cavity(
        self,
        cavstring: str,
        length: float,
        at: float,
        energy: float,
    ) -> tuple:
        """
        Convert an RF cavity definition into a first-order MAD-X ``MATRIX``
        element containing the Rosenzweig-Serafini accelerating-structure
        matrix (the same transverse model used by Ocelot, with eta = 1),
        followed by a thin ``RFCAVITY`` applying the energy gain and RF
        curvature. In the fixed-reference-momentum canonical coordinates
        (px = Px/P0) of a lattice segment the resulting 4x4 transverse matrix
        is exactly symplectic, so it can be used directly by the MAD-X
        thin-lens tracking and Twiss modules.

        Parameters
        ----------
        cavstring: str
            The full MAD-X element definition for the cavity
        length: float
            Physical length of the cavity [m]
        at: float
            Position of the cavity centre within the segment [m]
        energy: float
            Total beam (design) energy at the entrance of the cavity [eV]

        Returns
        -------
        tuple
            (MAD-X definitions string, energy at the exit of the cavity [eV])
        """
        m0 = self.particle_rest_energy_eV
        if ":=" in cavstring or energy <= m0:
            if energy <= m0:
                warn(
                    "MADX: beam energy unknown when writing the lattice -- "
                    "using a thin-kick cavity model. Call preProcess() "
                    "before write() to enable the rsmatrix cavity model."
                )
            return cavstring, energy
        elemname, etype, attrs = self.parse_madx_element(cavstring)
        if etype != "rfcavity":
            return cavstring, energy
        try:
            volt = float(attrs.get("volt", 0.0)) * 1e6  # MV -> eV
            lag = float(attrs.get("lag", 0.0))
            L = float(attrs.get("l", length))
        except ValueError:
            return cavstring, energy
        de = volt * np.sin(2 * np.pi * lag)
        if L <= 0 or abs(de) < 1e-9 * max(energy, 1.0):
            return cavstring, energy + de
        # Rosenzweig-Serafini matrix (pure pi-mode standing wave, eta = 1),
        # as implemented in the Ocelot CavityAtom first-order map
        cos_phi = np.sin(2 * np.pi * lag)  # = cos(phase) off-crest convention
        Ei = energy / m0
        Ef = (energy + de) / m0
        Ep = (Ef - Ei) / L
        alpha = np.sqrt(1.0 / 8.0) / cos_phi * np.log(Ef / Ei)
        sin_a, cos_a = np.sin(alpha), np.cos(alpha)
        r11 = cos_a - np.sqrt(2.0) * cos_phi * sin_a
        r12 = np.sqrt(8.0) * Ei / Ep * cos_phi * sin_a if abs(Ep) > 1e-10 else L
        r21 = -Ep / Ef * (cos_phi / np.sqrt(2.0) + np.sqrt(1.0 / 8.0) / cos_phi) * sin_a
        r22 = Ei / Ef * (cos_a + np.sqrt(2.0) * cos_phi * sin_a)
        # convert from trace-space (x, x') to the segment's canonical
        # coordinates (x, px = Px/P0) with P0 = P(entrance): the resulting
        # matrix has unit determinant
        Pi = np.sqrt(Ei**2 - 1.0)
        Pf = np.sqrt(Ef**2 - 1.0)
        m11, m12 = r11, r12
        m21, m22 = r21 * Pf / Pi, r22 * Pf / Pi
        matrixstr = (
            f"{elemname}_RSM: matrix, l = {L}, "
            f"rm11 = {m11}, rm12 = {m12}, rm21 = {m21}, rm22 = {m22}, "
            f"rm33 = {m11}, rm34 = {m12}, rm43 = {m21}, rm44 = {m22}, "
            f"at = {at};"
        )
        others = {k: v for k, v in attrs.items() if k not in ("l", "at")}
        cavstr = (
            f"{elemname}: rfcavity, l = 0, "
            + ", ".join([f"{k} = {v}" for k, v in others.items()])
            + f", at = {at + L / 2.0};"
        )
        return matrixstr + "\n" + cavstr, energy + de

    def slice_cavity(self, cavstring: str, length: float, at: float) -> str:
        """
        Subdivide an RF cavity definition into :attr:`~nslice_rfcavity`
        sub-cavities, each with 1/n of the voltage (and length), placed
        uniformly along the body of the structure. The MAD-X thin-lens
        tracking module applies each sub-cavity as a thin RF kick, with exact
        drifts in between, which reproduces the adiabatic damping of the
        transverse coordinates through the accelerating structure (a single
        lumped kick would let the beam expand at the injection energy over
        half the structure length before feeling any acceleration).

        The last slice keeps the original element name, so that observation
        points and Twiss-table lookups remain valid.

        Parameters
        ----------
        cavstring: str
            The full MAD-X element definition for the cavity
        length: float
            Physical length of the cavity [m]
        at: float
            Position of the cavity centre within the segment [m]

        Returns
        -------
        str
            The MAD-X definitions of the sub-cavities (or the original
            definition if it cannot safely be sliced)
        """
        n = int(self.nslice_rfcavity)
        if n <= 1 or length <= 0:
            return cavstring
        # deferred (":=") expressions cannot be rescaled safely
        if ":=" in cavstring:
            return cavstring
        elemname, etype, attrs = self.parse_madx_element(cavstring)
        if etype != "rfcavity":
            return cavstring
        try:
            volt = float(attrs.get("volt", 0.0))
            L = float(attrs.get("l", length))
        except ValueError:
            return cavstring
        others = {
            k: v for k, v in attrs.items() if k not in ("volt", "l", "at")
        }
        lines = []
        for k in range(n):
            slname = elemname if k == n - 1 else f"{elemname}_SL{k + 1}"
            slat = at - L / 2.0 + (k + 0.5) * L / n
            attrstr = ", ".join(
                [f"volt = {volt / n}", f"l = {L / n}"]
                + [f"{k2} = {v2}" for k2, v2 in others.items()]
                + [f"at = {slat}"]
            )
            lines.append(f"{slname}: rfcavity, {attrstr};")
        return "\n".join(lines)

    def write(self) -> None:
        """
        Create the lattice representation via
        :func:`~simba.Codes.MADX.MADX.madxLattice.writeElements` and save it
        as a MAD-X input file to `master_subdir`.
        """
        fulltext = self.writeElements()
        latticefile = (
            self.global_parameters["master_subdir"] + "/" + self.objectname + ".madx"
        )
        with open(latticefile, "w") as f:
            f.write(fulltext)
        self.files.append(latticefile)

    # ------------------------------------------------------------------
    # Pre-processing
    # ------------------------------------------------------------------
    def preProcess(self) -> None:
        """
        Get the initial particle distribution defined in
        `file_block['input']['prefix']` if it exists.
        """
        super().preProcess()
        prefix = self.get_prefix()
        prefix = prefix if self.trackBeam else prefix + self.particle_definition
        self.read_input_file(prefix, self.particle_definition)
        if self.initial_twiss["horizontal"]["beta"]:
            self.global_parameters["beam"].beam.rematchXPlane(
                **self.initial_twiss["horizontal"]
            )
        if self.initial_twiss["vertical"]["beta"]:
            self.global_parameters["beam"].beam.rematchYPlane(
                **self.initial_twiss["vertical"]
            )
        self.ref_s = self.global_parameters["beam"].s
        self.ref_idx = self.global_parameters["beam"].reference_particle_index
        self.pin = deepcopy(self.global_parameters["beam"])

    # ------------------------------------------------------------------
    # MAD-X interaction
    # ------------------------------------------------------------------
    def start_madx(self) -> Any:
        """
        Start a `cpymad` MAD-X interpreter, logging its output to
        `<lattice>.log` in `master_subdir`.

        Returns
        -------
        cpymad.madx.Madx
            The MAD-X instance
        """
        from cpymad.madx import Madx

        self.logfile = open(
            os.path.join(
                self.global_parameters["master_subdir"], self.objectname + ".log"
            ),
            "w",
        )
        madx = Madx(
            stdout=self.logfile,
            cwd=self.global_parameters["master_subdir"],
        )
        madx.option(echo=False, warn=True, info=False, twiss_print=False)
        if self.section.functional_definitions:
            madx.input(
                madx_functional_definitions(self.section.functional_definitions)
            )
        return madx

    def madx_beam_command(self, madx: Any, p0c: float, seqname: str) -> None:
        """
        Issue the MAD-X ``BEAM`` command for a segment, with the reference
        momentum `p0c` (in eV/c) and the mass/charge of the tracked species.
        """
        m0 = self.particle_rest_energy_eV
        chargesign = int(np.sign(np.mean(self.global_parameters["beam"].Q.val)) or -1)
        species = getattr(self.global_parameters["beam"], "species", "electron")
        if species in madx_particle_names:
            madx.input(
                f"beam, particle={madx_particle_names[species]}, pc={p0c / 1e9}, "
                f"sequence={seqname};"
            )
        else:
            madx.input(
                f"beam, mass={m0 / 1e9}, charge={chargesign}, pc={p0c / 1e9}, "
                f"sequence={seqname};"
            )

    def makethin(self, madx: Any, seqname: str) -> None:
        """
        Slice the (thick) segment sequence into thin lenses with the MAD-X
        ``MAKETHIN`` command (required by the thin-lens tracking module), and
        re-``USE`` the sequence.
        """
        madedge = "true" if self.makedipedge else "false"
        madx.input(
            f"""
            select, flag=makethin, clear;
            select, flag=makethin, class=matrix, slice=0;
            select, flag=makethin, class=quadrupole, slice={self.nslice_quadrupole};
            select, flag=makethin, class=sbend, slice={self.nslice_sbend};
            select, flag=makethin, class=rbend, slice={self.nslice_sbend};
            select, flag=makethin, class=rfcavity, slice=1;
            makethin, sequence={seqname}, style={self.makethin_style}, makedipedge={madedge};
            use, sequence={seqname};
            """
        )

    def observation_points(self, segnames: List) -> List:
        """
        The observation points for a segment: all zero-length diagnostics
        (`Screen`, `Marker` and `BPM` types) within the segment.

        Parameters
        ----------
        segnames: List
            Names of the elements in the segment

        Returns
        -------
        List
            (name, s position within segment) tuples
        """
        diag_names = [e.name for e in self.screens_and_markers_and_bpms]
        seg_s0 = self._sval_in[segnames[0]]
        obs = []
        for name in segnames:
            if name in diag_names and self._elem_dict[name].physical.length == 0:
                obs.append((name, self._sval_in[name] - seg_s0))
        return obs

    def run_track(
        self,
        madx: Any,
        coords: Dict,
        observe: List,
        numbers: np.ndarray = None,
    ) -> Dict:
        """
        Run the MAD-X thin-lens tracking module (``TRACK``/``START``/
        ``OBSERVE``/``RUN``/``ENDTRACK``) for one segment and return the
        contents of the ``trackone`` table.

        Parameters
        ----------
        madx: cpymad.madx.Madx
            The MAD-X instance
        coords: Dict
            The canonical starting coordinates
        observe: List
            (name, s) tuples at which to observe the beam
        numbers: np.ndarray, optional
            Particle numbers to assign (defaults to 1..N)

        Returns
        -------
        Dict
            Dictionary of arrays from the MAD-X `trackone` table
        """
        npart = len(coords["x"])
        madx.input("track, onepass, onetable;")
        startlines = []
        for i in range(npart):
            startlines.append(
                "start, x={:.15g}, px={:.15g}, y={:.15g}, py={:.15g}, "
                "t={:.15g}, pt={:.15g};".format(
                    coords["x"][i],
                    coords["px"][i],
                    coords["y"][i],
                    coords["py"][i],
                    coords["t"][i],
                    coords["pt"][i],
                )
            )
        # chunk the input to avoid very large single commands
        for i in range(0, len(startlines), 4096):
            madx.input("\n".join(startlines[i: i + 4096]))
        for name, sobs in observe:
            madx.input(f"observe, place={sanitize_string(name)};")
        maxaper = "{" + ",".join([str(v) for v in self.maxaper]) + "}"
        madx.input(f"run, turns=1, maxaper={maxaper};")
        madx.input("endtrack;")
        tbl = madx.table.trackone
        return {
            k: np.array(tbl[k])
            for k in ["number", "turn", "x", "px", "y", "py", "t", "pt", "s"]
        }

    def extract_observation(self, trackdata: Dict, s_target: float) -> Dict:
        """
        Extract the particle coordinates recorded at a given s position from
        the ``trackone`` table data, de-duplicated and ordered by particle
        number.

        Parameters
        ----------
        trackdata: Dict
            The `trackone` table data
        s_target: float
            The s position of the observation point within the segment

        Returns
        -------
        Dict
            Dictionary of coordinate arrays (including the surviving particle
            `number` array)
        """
        mask = (np.abs(trackdata["s"] - s_target) < 1e-8) & (trackdata["turn"] >= 1)
        if not np.any(mask) and abs(s_target) < 1e-8:
            # observation point at the very start of the segment -- use the
            # starting coordinates (turn 0)
            mask = (np.abs(trackdata["s"] - s_target) < 1e-8) & (
                trackdata["turn"] == 0
            )
        out = {k: trackdata[k][mask] for k in trackdata}
        order = np.argsort(out["number"], kind="stable")
        out = {k: out[k][order] for k in out}
        _, uidx = np.unique(out["number"], return_index=True)
        return {k: out[k][uidx] for k in out}

    def model_twiss_segment(
        self,
        madx: Any,
        seqname: str,
        init: Dict,
    ) -> Dict:
        """
        Compute the MAD-X model Twiss parameters for a segment with initial
        conditions `init`, and return the initial conditions for the next
        segment together with the Twiss data at each element.

        Parameters
        ----------
        madx: cpymad.madx.Madx
            The MAD-X instance
        seqname: str
            The name of the segment sequence
        init: Dict
            Initial Twiss conditions (betx, alfx, bety, alfy, dx, dpx, dy,
            dpy, mux, muy)

        Returns
        -------
        Dict
            Initial conditions for the next segment; the element-by-element
            data are accumulated into :attr:`~model_twiss`
        """
        try:
            madx.input(
                f"twiss, sequence={seqname}, betx={init['betx']}, alfx={init['alfx']}, "
                f"bety={init['bety']}, alfy={init['alfy']}, dx={init['dx']}, "
                f"dpx={init['dpx']}, dy={init['dy']}, dpy={init['dpy']};"
            )
            tw = madx.table.twiss
            names = [str(n).split(":")[0].lower() for n in tw["name"]]
            if len(names) == 0 or not names[0].startswith(seqname.lower()):
                raise ValueError(f"twiss table does not match segment {seqname}")
            data = {
                k: np.array(tw[k])
                for k in ["s", "betx", "alfx", "bety", "alfy", "dx", "dpx", "dy", "dpy", "mux", "muy"]
            }
        except Exception as e:
            warn(f"MAD-X twiss failed for {seqname}: {e}")
            return init
        for i, name in enumerate(names):
            self.model_twiss[name] = {
                "betx": data["betx"][i],
                "alfx": data["alfx"][i],
                "bety": data["bety"][i],
                "alfy": data["alfy"][i],
                "dx": data["dx"][i],
                "dpx": data["dpx"][i],
                "dy": data["dy"][i],
                "dpy": data["dpy"][i],
                "mux": data["mux"][i] + init["mux"],
                "muy": data["muy"][i] + init["muy"],
            }
        return {
            "betx": data["betx"][-1],
            "alfx": data["alfx"][-1],
            "bety": data["bety"][-1],
            "alfy": data["alfy"][-1],
            "dx": data["dx"][-1],
            "dpx": data["dpx"][-1],
            "dy": data["dy"][-1],
            "dpy": data["dpy"][-1],
            "mux": data["mux"][-1] + init["mux"],
            "muy": data["muy"][-1] + init["muy"],
        }

    # ------------------------------------------------------------------
    # Tracking
    # ------------------------------------------------------------------
    def initial_twiss_conditions(self, bm: rbf.beam) -> Dict:
        """Initial Twiss conditions for the model Twiss, from the beam"""
        try:
            return {
                "betx": float(bm.twiss.beta_x_corrected),
                "alfx": float(bm.twiss.alpha_x_corrected),
                "bety": float(bm.twiss.beta_y_corrected),
                "alfy": float(bm.twiss.alpha_y_corrected),
                "dx": 0.0,
                "dpx": 0.0,
                "dy": 0.0,
                "dpy": 0.0,
                "mux": 0.0,
                "muy": 0.0,
            }
        except Exception:
            return {
                "betx": 1.0,
                "alfx": 0.0,
                "bety": 1.0,
                "alfy": 0.0,
                "dx": 0.0,
                "dpx": 0.0,
                "dy": 0.0,
                "dpy": 0.0,
                "mux": 0.0,
                "muy": 0.0,
            }

    @staticmethod
    def rescale_twiss_init(init: Dict, ratio: float) -> Dict:
        """
        Re-reference a set of Twiss functions from one MAD-X reference
        momentum to another (``ratio`` = p0c_new / p0c_old).

        The MAD-X Twiss functions are defined in the canonical coordinates
        (x, px = Px/P0) of the segment, so they depend on the segment
        reference momentum. Since the beam is accelerated by the cavity at the
        end of each segment, the reference momentum changes at every segment
        boundary and the Twiss functions have to be transformed accordingly.

        Under P0 -> P0' the transverse coordinate x is unchanged while
        px -> px * P0/P0', so the canonical emittance scales as
        eps -> eps * P0/P0'. Hence beta (= sigma_x^2/eps) and the dispersion
        (per unit pt, which rescales the same way) are multiplied by `ratio`,
        while alpha and dpx/dpy are invariant.
        """
        if not np.isfinite(ratio) or ratio <= 0:
            return init
        out = dict(init)
        for key in ("betx", "bety", "dx", "dy"):
            out[key] = init[key] * ratio
        return out

    def store_beam_data(self, name: str, bm: rbf.beam, spos: float, zpos: float) -> None:
        """
        Store the beam statistics at an observation point into
        :attr:`~beam_data`, in a form that can be interpreted in the same way
        as the outputs of the other tracking codes.
        """
        try:
            eta_x = float(bm.twiss.eta_x)
            eta_xp = float(bm.twiss.eta_xp)
            eta_y = float(bm.twiss.eta_y)
            eta_yp = float(bm.twiss.eta_yp)
        except Exception:
            eta_x = eta_xp = eta_y = eta_yp = 0.0
        self.beam_data[name] = {
            "s": spos,
            "z": zpos,
            "t": float(np.mean(bm.t.val)),
            "cp": float(np.mean(bm.cp.val)),
            "sigma_x": float(bm.sigmas.sigma_x),
            "sigma_y": float(bm.sigmas.sigma_y),
            "sigma_xp": float(bm.sigmas.sigma_xp) if hasattr(bm.sigmas, "sigma_xp") else float(np.std(bm.xp.val)),
            "sigma_yp": float(bm.sigmas.sigma_yp) if hasattr(bm.sigmas, "sigma_yp") else float(np.std(bm.yp.val)),
            "sigma_t": float(bm.sigmas.sigma_t),
            "sigma_z": float(bm.sigmas.sigma_z),
            "sigma_cp": float(bm.sigmas.sigma_cp_eV),
            "mean_x": float(np.mean(bm.x.val)),
            "mean_y": float(np.mean(bm.y.val)),
            "ex": float(bm.emittance.ex),
            "ey": float(bm.emittance.ey),
            "enx": float(bm.emittance.enx),
            "eny": float(bm.emittance.eny),
            "ecnx": float(bm.emittance.ecnx),
            "ecny": float(bm.emittance.ecny),
            "beta_x_beam": float(bm.twiss.beta_x_corrected),
            "alpha_x_beam": float(bm.twiss.alpha_x_corrected),
            "beta_y_beam": float(bm.twiss.beta_y_corrected),
            "alpha_y_beam": float(bm.twiss.alpha_y_corrected),
            "eta_x_beam": eta_x,
            "eta_xp_beam": eta_xp,
            "eta_y_beam": eta_y,
            "eta_yp_beam": eta_yp,
        }

    def write_output_beam(self, name: str, bm: rbf.beam) -> None:
        """
        Write a beam distribution to an OpenPMD HDF5 file named after the
        element at which it was observed.
        """
        fname = os.path.join(
            self.global_parameters["master_subdir"], f"{name}.openpmd.hdf5"
        )
        rbf.openpmd.write_openpmd_beam_file(bm, fname)
        self.output_beams[name] = bm

    def run(self) -> None:
        """
        Run MAD-X tracking through all segments via `cpymad`, setting the
        MAD-X reference momentum of each segment to the mean momentum of the
        tracked bunch at its entrance, and re-referencing the canonical
        particle coordinates between segments.

        In full-beam mode (default), every particle in the (sampled) input
        distribution is tracked and the beam is recorded at every diagnostic;
        in :attr:`~single_particle` mode, the beam centroid and 12 probe
        particles are tracked to build the segment maps, which are then
        applied to the initial distribution to generate the output beam at
        the end of the line.
        """
        if len(self.seqstrings) == 0:
            self.writeElements()
        self.beam_data = {}
        self.model_twiss = {}
        self.output_beams = {}
        madx = self.start_madx()
        try:
            self.run_segments(madx)
        finally:
            try:
                madx.exit()
            except Exception:
                pass
            if self.logfile is not None:
                self.logfile.close()
                self.logfile = None

    def run_segments(self, madx: Any) -> None:
        """Track through each lattice segment in turn; see :func:`~run`."""
        sstart_lattice = self.start_s
        current_beam = deepcopy(self.pin)
        if not self.single_particle and self.sample_interval > 1:
            current_beam = self.sample_beam(current_beam, self.sample_interval)
        ref_idx = current_beam.reference_particle_index
        charge_total = abs(np.sum(np.array(current_beam.charge.val)))
        twiss_init = self.initial_twiss_conditions(current_beam)

        # store the beam data at the entrance of the lattice
        self.segment_p0c[self.start] = float(np.mean(current_beam.cp.val))
        self.store_beam_data(
            self.start,
            current_beam,
            self._sval_in[self.segments[0][0]] + sstart_lattice,
            self.startObject.physical.start.z,
        )

        p0c_prev = None
        for iseg, segnames in enumerate(self.segments):
            seqname = self.segment_name(iseg)
            seg_s0 = self._sval_in[segnames[0]]
            seg_s1 = self._sval_out[segnames[-1]]
            seg_len = seg_s1 - seg_s0
            p0c = float(np.mean(current_beam.cp.val))
            # the MAD-X Twiss functions are canonical w.r.t. the segment
            # reference momentum, which changes at every segment boundary
            if p0c_prev is not None and p0c_prev > 0:
                twiss_init = self.rescale_twiss_init(twiss_init, p0c / p0c_prev)
            p0c_prev = p0c
            for nm in segnames:
                self.segment_p0c[nm] = p0c
            if getattr(self, "verbose", False):
                print(
                    f"MADX [{self.objectname}] segment {iseg + 1}/{len(self.segments)}: "
                    f"s = {seg_s0:.3f} -> {seg_s1:.3f} m, p0c = {p0c / 1e6:.3f} MeV/c"
                )
            madx.input(self.seqstrings[iseg])
            self.madx_beam_command(madx, p0c, seqname)
            madx.use(sequence=seqname)
            self.makethin(madx, seqname)

            if self.write_model_twiss:
                twiss_init = self.model_twiss_segment(madx, seqname, twiss_init)

            if self.single_particle:
                current_beam = self.track_segment_single_particle(
                    madx, current_beam, p0c, seg_len, segnames,
                    seg_s0, sstart_lattice,
                )
                if segnames[-1] not in self.beam_data:
                    endelem = self._elements_with_drifts[segnames[-1]]
                    self.store_beam_data(
                        segnames[-1],
                        current_beam,
                        seg_s1 + sstart_lattice,
                        endelem.physical.end.z,
                    )
            else:
                current_beam = self.track_segment_beam(
                    madx,
                    current_beam,
                    p0c,
                    segnames,
                    seg_s0,
                    seg_len,
                    sstart_lattice,
                    charge_total,
                    ref_idx,
                )
                charge_total = abs(np.sum(np.array(current_beam.charge.val)))
                ref_idx = current_beam.reference_particle_index

        self.pout = current_beam
        # store/write the final beam at the end of the line
        endname = self.end
        endelem = self._elements_with_drifts[self.segments[-1][-1]]
        self.segment_p0c.setdefault(endname, p0c_prev)
        self.store_beam_data(
            endname,
            current_beam,
            self._sval_out[self.segments[-1][-1]] + sstart_lattice,
            endelem.physical.end.z,
        )
        self.write_output_beam(endname, current_beam)

    def track_segment_beam(
        self,
        madx: Any,
        current_beam: rbf.beam,
        p0c: float,
        segnames: List,
        seg_s0: float,
        seg_len: float,
        sstart_lattice: float,
        charge_total: float,
        ref_idx: int,
    ) -> rbf.beam:
        """
        Track the full particle distribution through one segment, recording
        (and writing) the beam distributions at each diagnostic within the
        segment; see :func:`~run`.

        Returns
        -------
        :class:`~simba.Modules.Beams.beam`
            The beam at the end of the segment
        """
        npart = len(current_beam.x.val)
        coords = current_beam.beam_to_madx_coords(p0c)
        tbar0 = coords["tbar"]
        observe = self.observation_points(segnames)
        trackdata = self.run_track(madx, coords, observe)
        charge_per_particle = charge_total / npart

        for name, s_local in observe:
            data = self.extract_observation(trackdata, s_local)
            if len(data["x"]) == 0:
                warn(f"MADX: no particles recorded at {name}")
                continue
            elem = self._elements_with_drifts[name]
            bm = self.pin.madx_coords_to_beam(
                data,
                p0c,
                tbar0,
                s_local,
                elem.physical.middle.z,
                elem.physical.middle.z,
                charge_per_particle * len(data["x"]),
                ref_index=self.reference_index(data["number"], ref_idx),
            )
            self.store_beam_data(
                name, bm, seg_s0 + s_local + sstart_lattice, elem.physical.middle.z
            )
            if not name == self.end:
                self.write_output_beam(name, bm)

        # end-of-segment beam (MAD-X automatically observes at the end of the
        # sequence)
        data = self.extract_observation(trackdata, seg_len)
        nlost = npart - len(data["x"])
        if nlost > 0:
            warn(f"MADX: {nlost} particles lost in segment")
        endelem = self._elements_with_drifts[segnames[-1]]
        newref = self.reference_index(data["number"], ref_idx)
        bm = self.pin.madx_coords_to_beam(
            data,
            p0c,
            tbar0,
            seg_len,
            endelem.physical.end.z,
            endelem.physical.end.z,
            charge_per_particle * len(data["x"]),
            ref_index=newref,
        )
        # record beam data at the exit of the segment (i.e. after the
        # accelerating cavity)
        segend_s = self._sval_out[segnames[-1]]
        if segnames[-1] not in self.beam_data:
            self.store_beam_data(
                segnames[-1], bm, segend_s + sstart_lattice, endelem.physical.end.z
            )
        return bm

    def reference_index(self, numbers: np.ndarray, ref_idx: int) -> int:
        """
        Get the index of the reference particle in the (possibly reduced)
        array of surviving particles, identified by their MAD-X `number`.
        """
        if ref_idx is None:
            return None
        target = int(ref_idx) + 1  # MAD-X numbers particles from 1
        idx = np.where(np.array(numbers).astype(int) == target)[0]
        if len(idx) == 0:
            return None
        return int(idx[0])

    def track_segment_single_particle(
        self,
        madx: Any,
        current_beam: rbf.beam,
        p0c: float,
        seg_len: float,
        segnames: List,
        seg_s0: float,
        sstart_lattice: float,
    ) -> rbf.beam:
        """
        Standard (single-particle) MAD-X tracking for one segment: the beam
        centroid is tracked, together with 12 probe trajectories used to
        build the linear map of the segment by finite differences. The full
        distribution is then transformed with the resulting map (centroid +
        R matrix); see :func:`~run`.

        The probes are observed at every diagnostic (`Screen`, `Marker`,
        `BPM`) within the segment as well as at its end, so that the map --
        and hence the transformed beam statistics -- are recorded along the
        whole line (via :func:`~store_beam_data`), not just at the segment
        boundaries (the accelerating cavities). Consistent with the
        ``single_particle`` contract, only the beam *statistics* are stored at
        the intermediate points; the beam distribution file is written once,
        for the end of the line (see :func:`~run_segments`).

        Returns
        -------
        :class:`~simba.Modules.Beams.beam`
            The (transformed) beam at the end of the segment
        """
        keys = ["x", "px", "y", "py", "t", "pt"]
        coords = current_beam.beam_to_madx_coords(p0c)
        tbar0 = coords["tbar"]
        zin = np.array([coords[k] for k in keys])
        centroid = np.mean(zin, axis=1)
        delta = abs(self.fd_delta)
        # centroid + (+/- delta) probes in each of the 6 canonical coordinates
        probes = [centroid]
        for k in range(6):
            for sign in (1, -1):
                probe = centroid.copy()
                probe[k] += sign * delta
                probes.append(probe)
        probes = np.array(probes).T
        probecoords = {k: probes[i] for i, k in enumerate(keys)}
        charge_total = abs(np.sum(np.array(current_beam.charge.val)))
        ref_index = current_beam.reference_particle_index
        # observe the probes at every diagnostic in the segment (and, via the
        # automatic end-of-sequence dump, at the segment end)
        observe = self.observation_points(segnames)
        trackdata = self.run_track(madx, probecoords, observe)

        def transformed_beam_at(s_local: float, zpos: float):
            """Beam obtained by applying the segment map (start -> ``s_local``,
            built from the 13 probes) to the full input distribution, or
            ``None`` if any probe was lost before ``s_local``."""
            data = self.extract_observation(trackdata, s_local)
            if len(data["x"]) != 13:
                return None
            zout = np.array([data[k] for k in keys])
            centroid_out = zout[:, 0]
            rmatrix = np.zeros((6, 6))
            for k in range(6):
                rmatrix[:, k] = (zout[:, 1 + 2 * k] - zout[:, 2 + 2 * k]) / (2 * delta)
            # transform the full distribution: z_out = c_out + R (z_in - c_in)
            transformed = centroid_out[:, np.newaxis] + rmatrix @ (
                zin - centroid[:, np.newaxis]
            )
            newcoords = {k: transformed[i] for i, k in enumerate(keys)}
            return self.pin.madx_coords_to_beam(
                newcoords, p0c, tbar0, s_local, zpos, zpos, charge_total,
                ref_index=ref_index,
            )

        # record the beam statistics at each diagnostic within the segment (no
        # beam file is written here -- only the end-of-line beam is, in run)
        for name, s_local in observe:
            elem = self._elements_with_drifts[name]
            bm = transformed_beam_at(s_local, elem.physical.middle.z)
            if bm is None:
                warn(f"MADX single-particle: probe particles lost at {name}")
                continue
            self.store_beam_data(
                name, bm, seg_s0 + s_local + sstart_lattice, elem.physical.middle.z
            )

        endelem = self._elements_with_drifts[segnames[-1]]
        bm_end = transformed_beam_at(seg_len, endelem.physical.end.z)
        if bm_end is None:
            raise RuntimeError(
                "MADX single-particle tracking lost probe particles at the "
                "segment end"
            )
        return bm_end

    def sample_beam(self, bm: rbf.beam, interval: int) -> rbf.beam:
        """
        Downsample a beam by the given interval, conserving the total charge.
        """
        newbeam = deepcopy(bm)
        nb = newbeam._beam
        idx = slice(None, None, int(interval))
        for key in ["x", "y", "z", "t", "px", "py", "pz", "nmacro", "status",
                    "particle_mass", "particle_rest_energy",
                    "particle_rest_energy_eV", "particle_charge"]:
            if hasattr(nb, key) and getattr(nb, key) is not None:
                val = getattr(nb, key)
                try:
                    setattr(nb, key, UnitValue(np.array(val.val)[idx], units=val.units))
                except Exception:
                    pass
        nb.set_total_charge(np.sum(np.array(bm.charge.val)))
        refidx = bm.reference_particle_index
        if refidx is not None and int(refidx) % int(interval) == 0:
            newbeam.reference_particle_index = int(refidx) // int(interval)
        else:
            newbeam.reference_particle_index = None
        return newbeam

    # ------------------------------------------------------------------
    # Post-processing
    # ------------------------------------------------------------------
    def postProcess(self) -> None:
        """
        Assemble the collected beam statistics and MAD-X model Twiss
        parameters into a Twiss summary file
        (``<lattice>_twiss.madx.hdf5``, readable by
        :func:`simba.Modules.Twiss.load_directory`), and update the global
        beam distribution with the beam at the end of the line.
        """
        super().postProcess()
        if len(self.beam_data) == 0:
            warn("MADX: no tracking data to post-process")
            return
        m0 = self.particle_rest_energy_eV
        rows = sorted(self.beam_data.items(), key=lambda kv: kv[1]["s"])
        twsdat = {
            "element_name": np.array([name for name, _ in rows], dtype="S"),
            "lattice_name": np.array([self.objectname for _ in rows], dtype="S"),
        }
        for key in [
            "s", "z", "t", "cp", "sigma_x", "sigma_y", "sigma_xp", "sigma_yp",
            "sigma_t", "sigma_z", "sigma_cp", "mean_x", "mean_y", "enx", "eny",
            "ex", "ey", "ecnx", "ecny", "beta_x_beam", "alpha_x_beam",
            "beta_y_beam", "alpha_y_beam", "eta_x_beam", "eta_xp_beam",
            "eta_y_beam", "eta_yp_beam",
        ]:
            twsdat[key] = np.array([d[key] for _, d in rows])
        cp = twsdat["cp"]
        E = np.sqrt(cp**2 + m0**2)
        twsdat["kinetic_energy"] = E - m0
        twsdat["gamma"] = E / m0
        twsdat["p"] = cp * elementary_charge / speed_of_light
        twsdat["mean_cp"] = cp
        twsdat["sigma_p"] = twsdat["sigma_cp"] / cp
        twsdat["enz"] = np.zeros(len(rows))
        twsdat["ez"] = np.zeros(len(rows))
        twsdat["beta_z"] = np.zeros(len(rows))
        twsdat["alpha_z"] = np.zeros(len(rows))
        twsdat["gamma_z"] = np.zeros(len(rows))
        # model twiss values (fall back to the beam values if the model
        # twiss is not available at an element)
        model_keys = {
            "beta_x": ("betx", "beta_x_beam"),
            "alpha_x": ("alfx", "alpha_x_beam"),
            "beta_y": ("bety", "beta_y_beam"),
            "alpha_y": ("alfy", "alpha_y_beam"),
            "eta_x": ("dx", "eta_x_beam"),
            "eta_xp": ("dpx", "eta_xp_beam"),
            "eta_y": ("dy", "eta_y_beam"),
            "eta_yp": ("dpy", "eta_yp_beam"),
            "mux": ("mux", None),
            "muy": ("muy", None),
        }
        scale = np.array(
            [
                d["cp"] / self.segment_p0c[name]
                if self.segment_p0c.get(name, 0) > 0
                else 1.0
                for name, d in rows
            ]
        )
        canonical_scaling = {"beta_x", "beta_y", "eta_x", "eta_y"}
        for key, (mkey, fallback) in model_keys.items():
            vals = []
            for i, (name, d) in enumerate(rows):
                mname = sanitize_string(name).lower()
                if mname in self.model_twiss:
                    val = self.model_twiss[mname][mkey]
                    if key in canonical_scaling:
                        val = val * scale[i]
                    vals.append(val)
                elif fallback is not None:
                    vals.append(d[fallback])
                else:
                    vals.append(0.0)
            twsdat[key] = np.array(vals)
        twsdat["gamma_x"] = (1 + twsdat["alpha_x"] ** 2) / twsdat["beta_x"]
        twsdat["gamma_y"] = (1 + twsdat["alpha_y"] ** 2) / twsdat["beta_y"]
        self.tws = twsdat
        save_madx_twiss_hdf(
            self,
            filename=(
                f'{self.global_parameters["master_subdir"]}/'
                f"{self.objectname}_twiss.madx.hdf5"
            ),
            twiss=twsdat,
        )
        # update the global beam object with the distribution at the end of
        # the line, so that subsequent lattices start from it
        endfile = os.path.join(
            self.global_parameters["master_subdir"], f"{self.end}.openpmd.hdf5"
        )
        if os.path.isfile(endfile):
            rbf.openpmd.read_openpmd_beam_file(
                self.global_parameters["beam"], endfile
            )
