[classes]
astraLattice = "AstraLattice"
cheetahLattice = "CheetahLattice"
csrtrackLattice = "CsrTrackLattice"
elegantLattice = "ElegantLattice"
elegantOptimisation = "ElegantOptimisation"
elegant_error_elements_command = "ElegantErrorElementsCommand"
elegant_floor_coordinates_command = "ElegantFloorCoordinatesCommand"
elegant_global_settings_command = "ElegantGlobalSettingsCommand"
elegant_matrix_output_command = "ElegantMatrixOutputCommand"
elegant_run_control_command = "ElegantRunControlCommand"
elegant_run_setup_command = "ElegantRunSetupCommand"
elegant_scan_elements_command = "ElegantScanElementsCommand"
elegant_sdds_beam_command = "ElegantSddsBeamCommand"
elegant_track_command = "ElegantTrackCommand"
elegant_twiss_output_command = "ElegantTwissOutputCommand"
executable = "Executable"
frameworkGenerator = "FrameworkGenerator"
genesisCommandFile = "GenesisCommandFile"
genesisLattice = "GenesisLattice"
genesis_alter_beam_command = "GenesisAlterBeamCommand"
genesis_alter_setup_command = "GenesisAlterSetupCommand"
genesis_beam_command = "GenesisBeamCommand"
genesis_efield_command = "GenesisEfieldCommand"
genesis_field_command = "GenesisFieldCommand"
genesis_importbeam_command = "GenesisImportbeamCommand"
genesis_importdistribution_command = "GenesisImportdistributionCommand"
genesis_importfield_command = "GenesisImportfieldCommand"
genesis_importtransformation_command = "GenesisImporttransformationCommand"
genesis_lattice_command = "GenesisLatticeCommand"
genesis_profile_const_command = "GenesisProfileConstCommand"
genesis_profile_file_command = "GenesisProfileFileCommand"
genesis_profile_gauss_command = "GenesisProfileGaussCommand"
genesis_profile_polynom_command = "GenesisProfilePolynomCommand"
genesis_profile_step_command = "GenesisProfileStepCommand"
genesis_sequence_const_command = "GenesisSequenceConstCommand"
genesis_sequence_polynom_command = "GenesisSequencePolynomCommand"
genesis_sequence_power_command = "GenesisSequencePowerCommand"
genesis_sequence_random_command = "GenesisSequenceRandomCommand"
genesis_setup_command = "GenesisSetupCommand"
genesis_sort_command = "GenesisSortCommand"
genesis_sponrad_command = "GenesisSponradCommand"
genesis_time_command = "GenesisTimeCommand"
genesis_track_command = "GenesisTrackCommand"
genesis_wake_command = "GenesisWakeCommand"
genesis_write_command = "GenesisWriteCommand"
gptLattice = "GptLattice"
ocelotLattice = "OcelotLattice"
opalLattice = "OpalLattice"
sddsFile = "SddsFile"
waketLattice = "WaketLattice"
xsuiteLattice = "XsuiteLattice"

[functions]
_write_ASTRA = "_write_astra"
createCommandFiles = "create_command_files"
define_ASTRAgenerator_command = "define_astra_generator_command"
find_ASTRA_filename = "find_astra_filename"
getNCPU = "get_ncpu"
kernel_K0 = "kernel_k0"
kernel_K1 = "kernel_k1"
kernel_K2 = "kernel_k2"
postProcess = "post_process"
preProcess = "pre_process"
processElementErrors = "process_element_errors"
processElementScan = "process_element_scan"
processRunSettings = "process_run_settings"
setCSRMode = "set_csr_mode"
writeElements = "write_elements"

[globals]
allowedKeyWords = "allowed_key_words"
commandFiles = "command_files"
commandFilesOrder = "command_files_order"
doLoss = "do_loss"
doSpread = "do_spread"
elementErrors = "element_errors"
endScreenObject = "end_screen_object"
isTime = "is_time"
override_meanBz = "override_mean_bz"
section_header_text_ASTRA = "section_header_text_astra"
trackBeam = "track_beam"
