[classes]
chicane = "Chicane"
element_group = "ElementGroup"
frameworkCommand = "FrameworkCommand"
frameworkCounter = "FrameworkCounter"
frameworkDirectory = "FrameworkDirectory"
frameworkGroup = "FrameworkGroup"
frameworkLattice = "FrameworkLattice"
frameworkObject = "FrameworkObject"
getGrids = "GetGrids"
global_error = "GlobalError"
r56_group = "R56Group"
runSetup = "RunSetup"
s_chicane = "SChicane"

[functions]
_addLists = "_add_lists"
_write_ASTRA = "_write_astra"
_write_GPT = "_write_gpt"
add_Error = "add_error"
add_Generator = "add_generator"
allElementObjects = "all_element_objects"
allGroupObjects = "all_group_objects"
change_Lattice_Code = "change_lattice_code"
change_Parameter = "change_parameter"
checkValue = "check_value"
createDrifts = "create_drifts"
createOptionalString = "create_optional_string"
endObject = "end_object"
findS = "find_s"
findSetting = "find_setting"
findSettingValue = "find_setting_value"
formatOptionalString = "format_optional_string"
getElement = "get_element"
getElementType = "get_element_type"
getElems = "get_elems"
getGridSizes = "get_grid_sizes"
getInitialTwiss = "get_initial_twiss"
getNames = "get_names"
getParameter = "get_parameter"
getSNames = "get_s_names"
getSNamesElems = "get_s_names_elems"
getSValues = "get_s_values"
getSValuesElements = "get_s_values_elements"
getScreen = "get_screen"
getScreenNames = "get_screen_names"
getZNamesElems = "get_z_names_elems"
getZValues = "get_z_values"
getZValuesElements = "get_z_values_elements"
get_Parameter = "get_parameter"
lineReplaceFunction = "line_replace_function"
loadElementErrors = "load_element_errors"
loadParametersFile = "load_parameters_file"
loadSettings = "load_settings"
load_Elements_File = "load_elements_file"
modifyElement = "modify_element"
modifyElementType = "modify_element_type"
modifyElements = "modify_elements"
modifyLattice = "modify_lattice"
modifyLattices = "modify_lattices"
offsetElements = "offset_elements"
postProcess = "post_process"
preProcess = "pre_process"
pushRunSettings = "push_run_settings"
readFile = "read_file"
read_Lattice = "read_lattice"
replaceString = "replace_string"
rotationMatrix = "rotation_matrix"
saveFile = "save_file"
saveParametersFile = "save_parameters_file"
setElementScan = "set_element_scan"
setElementType = "set_element_type"
setMasterLatticeLocation = "set_master_lattice_location"
setNRuns = "set_n_runs"
setSeedValue = "set_seed_value"
setSimCodesLocation = "set_sim_codes_location"
setSubDirectory = "set_sub_directory"
setupGeneratorDefaults = "setup_generator_defaults"
setupLAURA = "setup_laura"
sortByPositionFunction = "sort_by_position_function"
startObject = "start_object"
updateElements = "update_elements"
updateGlobalParameters = "update_global_parameters"
updateRunSettings = "update_run_settings"
write_Elegant = "write_elegant"
write_Genesis = "write_genesis"
write_MAD8 = "write_mad8"

[globals]
allElements = "all_elements"
commandObjects = "command_objects"
elementObjects = "element_objects"
elements_Elegant = "elements_elegant"
fileSettings = "file_settings"
generatorSettings = "generator_settings"
globalSettings = "global_settings"
groupObjects = "group_objects"
groupSettings = "group_settings"
latticeClasses = "lattice_classes"
latticeObjects = "lattice_objects"
original_elementObjects = "original_element_objects"
runSettings = "run_settings"
settingsFilename = "settings_filename"
type_conversion_rules_Elegant = "type_conversion_rules_elegant"
type_conversion_rules_Names = "type_conversion_rules_names"
type_conversion_rules_Opal = "type_conversion_rules_opal"
