[classes]
beam = "Beam"
beamGroup = "BeamGroup"
centroids = "Centroids"
emittance = "Emittance"
kde = "Kde"
particlesGroup = "ParticlesGroup"
sigmas = "Sigmas"
slice = "Slice"
stats = "Stats"
statsGroup = "StatsGroup"
twiss = "Twiss"

[functions]
BetaGamma = "beta_gamma"
Brho = "brho"
Bx = "bx"
By = "by"
Bz = "bz"
CDF = "cdf"
CEn = "c_en"
Ccp = "ccp"
Cgamma = "cgamma"
Cp = "cp"
Cpx = "cpx"
Cpy = "cpy"
Cpz = "cpz"
Ct = "ct"
Cx = "cx"
Cxp = "cxp"
Cy = "cy"
Cyp = "cyp"
Cz = "cz"
Ex = "ex"
Ey = "ey"
Ez = "ez"
FWHM = "fwhm"
PDF = "pdf"
PDFI = "pdfi"
Particles = "particles"
Q = "q"
St = "st"
Sx = "sx"
Sy = "sy"
Sz = "sz"
computeCorrelations = "compute_correlations"
getEllipsoidVolume = "get_ellipsoid_volume"
getMinVolEllipse = "get_min_vol_ellipse"
getScreen = "get_screen"
getScreenImage = "get_screen_image"
getScreens = "get_screens"
interpret_cheetah_ParticleBeam = "interpret_cheetah_particle_beam"
load_HDF5_summary_file = "load_hdf5_summary_file"
mvesliceAnalysis = "mveslice_analysis"
performTransformation = "perform_transformation"
performTransformationPeakISlice = "perform_transformation_peak_i_slice"
plotEllipsoid = "plot_ellipsoid"
plotScreenImage = "plot_screen_image"
read_HDF5_beam_file = "read_hdf5_beam_file"
read_SDDS_beam_file = "read_sdds_beam_file"
rematchXPlane = "rematch_x_plane"
rematchXPlanePeakISlice = "rematch_x_plane_peak_i_slice"
rematchYPlane = "rematch_y_plane"
rematchYPlanePeakISlice = "rematch_y_plane_peak_i_slice"
remove_Hull = "remove_hull"
rotate_beamXZ = "rotate_beam_xz"
save_HDF5_summary_file = "save_hdf5_summary_file"
sliceAnalysis = "slice_analysis"
slice_6D_Volume = "slice_6d_volume"
unrotate_beamXZ = "unrotate_beam_xz"
volume6D = "volume_6d"
write_HDF5_beam_file = "write_hdf5_beam_file"
write_HDF5_summary_file = "write_hdf5_summary_file"
write_SDDS_beam_file = "write_sdds_beam_file"
write_SDDS_file = "write_sdds_file"

[globals]
_cp_Bins = "_cp_bins"
_t_Bins = "_t_bins"
fastKDE_installed = "fast_kde_installed"
hullP = "hull_p"
