[classes]
SDDS_Types = "SddsTypes"
constraintsClass = "ConstraintsClass"
field = "FieldMap"
gdf_beam = "GdfBeam"
gdf_emit = "GdfEmit"
initialTwiss = "InitialTwiss"
latticeDraw = "LatticeDraw"
lineElement = "LineElement"
magnet_plotting_data = "MagnetPlottingData"
mainWindow = "MainWindow"
matrices = "Matrices"
multiAxisPlotWidget = "MultiAxisPlotWidget"
multiPlotWidget = "MultiPlotWidget"
optimiser = "Optimiser"
pmd_unit = "PmdUnit"
rectangleElement = "RectangleElement"
twiss = "Twiss"
twissParameter = "TwissParameter"
zmqClient = "ZmqClient"
zmqServer = "ZmqServer"

[functions]
ASTRA_TW_FieldMap = "astra_tw_field_map"
R = "r"
_Name = "_name"
addCurve = "add_curve"
addShadowPen = "add_shadow_pen"
boundingRect = "bounding_rect"
clearCurves = "clear_curves"
constraintsList = "constraints_list"
cumulativeR = "cumulative_r"
curveClicked = "curve_clicked"
defineElements = "define_elements"
eaMuPlusLambda = "ea_mu_plus_lambda"
eaSimple = "ea_simple"
formatDict = "format_dict"
gaSimple = "ga_simple"
generatePicture = "generate_picture"
generate_R_matrix = "generate_r_matrix"
highlightPlot = "highlight_plot"
individualR = "individual_r"
reScaleLattice = "re_scale_lattice"
read_GPT_twiss_files = "read_gpt_twiss_files"
read_HDF5_field_file = "read_hdf5_field_file"
read_HDF5_twiss_file = "read_hdf5_twiss_file"
read_SDDS_field_file = "read_sdds_field_file"
removeCurve = "remove_curve"
removeData = "remove_data"
removeShadowPen = "remove_shadow_pen"
save_HDF5_twiss_file = "save_hdf5_twiss_file"
setOffset = "set_offset"
setPenAlpha = "set_pen_alpha"
setScale = "set_scale"
set_E0 = "set_e0"
unHighlightPlot = "un_highlight_plot"
unitDimension = "unit_dimension"
unitSI = "unit_si"
unitSymbol = "unit_symbol"
updateCurve = "update_curve"
updateCurveHighlights = "update_curve_highlights"
updateMultiAxisPlot = "update_multi_axis_plot"
updateViews = "update_views"
write_HDF5_field_file = "write_hdf5_field_file"
write_HDF5_twiss_file = "write_hdf5_twiss_file"
write_SDDS_field_file = "write_sdds_field_file"

[globals]
constraintsList = "constraints_list"
dataObject = "data_object"
elegantData = "elegant_data"
elegantTwiss = "elegant_twiss"
highlightCurveSignal = "highlight_curve_signal"
plotParams = "plot_params"
unHighlightCurveSignal = "un_highlight_curve_signal"
