from cheetah.accelerator import (  # noqa: F401
    BPM,
    Aperture,
    Cavity,
    CustomTransferMap,
    Dipole,
    Drift,
    Element,
    HorizontalCorrector,
    Marker,
    Quadrupole,
    RBend,
    Screen,
    Segment,
    Sextupole,
    Solenoid,
    SpaceChargeKick,
    TransverseDeflectingCavity,
    Undulator,
    VerticalCorrector,
)

cheetah_conversion_rules = {
    "dipole": Dipole,
    "solenoid": Solenoid,
    "quadrupole": Quadrupole,
    "sextupole": Sextupole,
    "octupole": Drift,
    "beam_position_monitor": Screen,
    "beam_arrival_monitor": Screen,
    "bunch_length_monitor": Screen,
    "screen": Screen,
    "rcollimator": Aperture,
    "collimator": Aperture,
    "monitor": Screen,
    "wall_current_monitor": Drift,
    "integrated_current_transformer": Drift,
    "faraday_cup": Drift,
    "cavity": Cavity,
    "rf_deflecting_cavity": TransverseDeflectingCavity,
    "aperture": Screen,
    "shutter": Drift,
    "valve": Drift,
    "bellows": Drift,
    "cleaner": Drift,
    "lscdrift": Drift,
    "edrift": Drift,
    "csrdrift": Drift,
    "kicker": HorizontalCorrector,
    "marker": Screen,
    "wakefield": Drift,
}
